### ISSUE TITLE
QR code scan 

### ISSUE THREAD

**Issue by samgo1** [aa-software2112/SOEN390_SimpleCamera#100]
As a user, I would like to have the option to choose QR code scanner.

- [x] Implement mockup #101 @Lussier115  [Story points: 1] [Ideal hours: 2]
- [x] Implement frontend #103 @aa-software2112 [Story points: 1] [Ideal hours: 5]
- [x] Implement backend #107 @aa-software2112  [Story points: 5] [Ideal hours: 10]
- [x] Implement unit tests #102  @samgo1 [Story points: 2] [Ideal hours: 5]
- [x] Implement acceptance test #104 @KrishnaPatel1  [Story points: 2] [Ideal hours: 3] 

[Story points: 5]
[Ideal hours: 25]
