### ISSUE TITLE
Stamp caption on top of last-taken image

### ISSUE THREAD

**Issue by aa-software2112** [aa-software2112/SOEN390_SimpleCamera#119]
As a user, I would like to be able to type and add a text caption after taking a photo.

- [x] Make the mockup #125 @anthonyle17  [Story points: 1] [Ideal hours: 3]
- [x] Develop frontend #126 @anthonyle17 [Story points: 3] [Ideal hours: 5]
- [x] Develop backend #127 @aa-software2112  [Story points: 5] [Ideal hours: 8]
- [x] Develop unit tests #128 @Lussier115  [Story points: 2] [Ideal hours: 3]
- [x] Develop acceptance tests #129 @samgo1 [Story points: 3] [Ideal hours: 6]

[Story points: 5]
[Ideal hours:  26]
