### ISSUE TITLE
Create a countdown timer prior to taking a picture

### ISSUE THREAD

**Issue by KrishnaPatel1** [aa-software2112/SOEN390_SimpleCamera#16]
- [x] Create a mockup (#17) [1 hours] @laurawheatley @Lussier115  
- [x] Implement the frontend aspect of the timer (#19) [3 hours] @Lussier115 
- [x] Implement backend aspect of the timer (#20) [8 hours] @lkadian @laurawheatley @samgo1 
- [x] Create unit test (#18) [6 hours] @laurawheatley  @anthonyle17 
- [x] Create acceptance test (#21) [4 hours] @aa-software2112 @KrishnaPatel1 

[Story points: 5]
[Ideal hours: 22]
