### ISSUE TITLE
GPS tag of photo and video location

### ISSUE THREAD

**Issue by aa-software2112** [aa-software2112/SOEN390_SimpleCamera#35]
As a user, I would like to have the option to enable GPS-tagging the photos I take to be able to remember where I've taken the photos.

- [x] Make the mockup #81 @aa-software2112 [Story points: 1] [Ideal hours: 2]
- [x] Develop frontend #83 @aa-software2112 [Story points: 2] [Ideal hours: 3]
- [x] Develop backend #95 @laurawheatley @anthonyle17 [Story points: 5] [Ideal hours: 15]
- [x] Develop unit tests #94 @laurawheatley @anthonyle17 [Story points: 3] [Ideal hours: 7]
- [x] Develop acceptance tests #96  @lkadian  [Story points: 2] [Ideal hours: 5]

[Story points: 8]
[Ideal hours: 30]
