### ISSUE TITLE
Burst-shot mode

### ISSUE THREAD

**Issue by samgo1** [aa-software2112/SOEN390_SimpleCamera#39]
As a user, I would like to have a burst-shot mode to be able to take clear photos of fast moving objects.

- [x] Make mockup #47 @laurawheatley [Ideal hours: 1] [Story points: 3]
- [x] Develop frontend #60 @laurawheatley [Ideal hours: 3] [Story points: 2]
- [x] Develop backend #65 @samgo1 @Lussier115 [Ideal hours: 17] [Story points: 5]
- [x] Develop unit tests #64 @lkadian @KrishnaPatel1 [Ideal hours: 7] [Story points: 2]
- [x] Develop acceptance tests #61 @aa-software2112 @laurawheatley  [Ideal hours: 7] [Story points: 5]

[Story points: 8]
[Ideal hours: 35]
