### ISSUE TITLE
Applying a filter real time for photos

### ISSUE THREAD

**Issue by lkadian** [aa-software2112/SOEN390_SimpleCamera#40]
As a user, I would like to have the option to choose a filter before taking a picture (e.g. black and white filter) to be able to customize the photos I take.

- [x] Implement mockup #82 @lkadian [Story points: 1] [Ideal hours: 2]
- [x] Implement frontend #93 @lkadian [Story points: 1] [Ideal hours: 5]
- [x] Implement backend #91 @Lussier115  @KrishnaPatel1 [Story points: 5] [Ideal hours: 10] 
- [x] Implement unit tests #90 @samgo1 [Story points: 3] [Ideal hours: 10] 
- [x] Implement acceptance test #92 @samgo1 [Story points: 2] [Ideal hours: 8] 

[Story points: 13]
[Ideal hours: 35]
