### ISSUE TITLE
Send last photo/video to a contact from within the app

### ISSUE THREAD

**Issue by laurawheatley** [aa-software2112/SOEN390_SimpleCamera#43]
As a user, I would like to be able to share the picture or video I've taken in order to keep my social circle up-to-date.

- [x] Implement mockup #120 @KrishnaPatel1 [Story points: 1] [Ideal hours: 2]
- [x] Implement frontend #121 @KrishnaPatel1  [Story points: 2] [Ideal hours: 5]
- [x] Implement backend  #122 @samgo1 @lkadian [Story points: 8] [Ideal hours: 10]
- [x] Implement unit tests #123 @laurawheatley [Story points: 2] [Ideal hours: 5]
- [x] Implement acceptance test #124 @lkadian [Story points: 2] [Ideal hours: 3] 

[Story points: 8]
[Ideal hours: 25]
