### ISSUE TITLE
Redesign the user interface

### ISSUE THREAD

**Issue by anthonyle17** [aa-software2112/SOEN390_SimpleCamera#44]
As a user, I would like a redesigned UI to be able to access features and settings faster and more easily.

- [x] Make the mockup #49 @KrishnaPatel1 [Story points: 1] [Ideal hours: 4]
- [x] Develop frontend #57 @KrishnaPatel1 [Story points: 2] [Ideal hours: 4]
- [x] Develop backend #58 @lkadian [Story points: 1] [Ideal hours: 3]
- [x] Develop acceptance tests #59 @Lussier115 [Story points: 1] [Ideal hours: 4]

[Story points: 3]
[Ideal hours: 15]
