### ISSUE TITLE
Display the amount of space left on disk

### ISSUE THREAD

**Issue by samgo1** [aa-software2112/SOEN390_SimpleCamera#46]
Display the amount of space left on disk, and the amount of hours, minutes, seconds remaining of possible video recording (for the currently selected Mbps). 
 

- [x] Make the mockup #109 @laurawheatley  [Story points: 1] [Ideal hours: 2]
- [x] Develop frontend #110 @laurawheatley [Story points: 2] [Ideal hours: 2]
- [x] Develop backend #112 @lkadian [Story points: 5] [Ideal hours: 10]
- [x] Develop unit tests #113 @Lussier115 [Story points: 2] [Ideal hours: 3]
- [x] Develop acceptance tests #114 @anthonyle17 [Story points: 2] [Ideal hours: 5]

[Story points: 5]
[Ideal hours: 22]
