### ISSUE TITLE
Setting up Travis CI

### ISSUE THREAD

**Issue by samgo1** [aa-software2112/SOEN390_SimpleCamera#5]
As a developer, I would like to set up Travis CI for continuous integration.

- [x] Integrating Travis CI to the repo #14 [1 hour] @samgo1 
- [x] Write an initial passing script #15 [1 hour] @samgo1 
- [x] Choose and integrate a testing framework #11 [2 hours] @KrishnaPatel1 @Lussier115 
- [x] Write 3 unit tests to ensure it is functioning in the Travis build #12 [2 hours] @aa-software2112 @lkadian @anthonyle17 
- [x] Choose and integrate an emulator for integration and acceptance testing in Travis #13 [2 hours] @aa-software2112 @Lussier115 
- [x] Remove "clean" and "release" build within Travis @KrishnaPatel1 

Please refer to the Wiki for more information on Testing.

[Story points: 3]
[Ideal hours: 8]
