### ISSUE TITLE
Architectural Decomposition

### ISSUE THREAD

**Issue by samgo1** [aa-software2112/SOEN390_SimpleCamera#6]
As a developer, I would like to recover the architecture for the application to better understand the functionality and structure of the system as a whole.

- [x] Identify components of the app #7 [3 hours] @samgo1 @laurawheatley 
- [x] Identify the connectors #8 [3 hours] @samgo1 @KrishnaPatel1 
- [x] Make a class diagram to represent them #9 [1 hour] @lkadian @Lussier115 
- [x] Make a layer diagram #10 [1 hour] @laurawheatley @samgo1 

[Story points: 5]
[Ideal hours: 8]
